{
 "title": "Demo Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "traces_span_metrics_duration_milliseconds_bucket"
    }
   }
  ]
 },
 "panels": [
  { "title": "Spanmetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency for ${service}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile999"
    }
   ]
  },
  {
   "title": "Error Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": " sum by (span_name) (rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Requests Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(traces_span_metrics_duration_milliseconds_count{service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  { "title": "Application Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "${service} Log entries by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where resource.service.name=\"${service}\"\n| stats count() by severity.text",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "${service} Logs (100 recent entries)",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where resource.service.name=\"${service}\"| sort - observedTimestamp | head 100",
     "timeField": "observedTimestamp"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Python services (CPU%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_runtime_cpython_cpu_time_seconds_total{type=~\"system\"}[$__rate_interval])*100",
     "legendFormat": "{{job}} ({{type}})"
    },
    {
     "expr": "rate(process_runtime_cpython_cpu_time_seconds_total{type=~\"user\"}[$__rate_interval])*100",
     "legendFormat": "{{job}} ({{type}})"
    }
   ]
  },
  {
   "title": "Python services (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_cpython_memory_bytes{type=\"rss\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Recommendations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(app_recommendations_counter_total{recommendation_type=\"catalog\"}[$__rate_interval])",
     "legendFormat": "recommendations"
    }
   ]
  },
  {
   "title": "Quote Service batch span processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(otel_trace_span_processor_spans{job=\"opentelemetry-demo/quote\"}[2m])*120",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}
{
 "title": "Cart Service Exemplars",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "GetCart Exemplars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "95th Pct Cart GetCart Latency with Exemplars",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_cart_get_cart_latency_bucket[$__rate_interval])))",
     "legendFormat": "p95 GetCart"
    }
   ]
  },
  {
   "title": "GetCart Latency Heatmap with Exemplars",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (rate(app_cart_get_cart_latency_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "AddItem Exemplars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "AddItem Latency Heatmap with Exemplars",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(le) (rate(app_cart_add_item_latency_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "95th Pct Cart AddItem Latency with Exemplars",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_cart_add_item_latency_bucket[$__rate_interval])))",
     "legendFormat": "p95 AddItem"
    }
   ]
  }
 ]
}
{
 "title": "Opentelemetry Collector Data Flow",
 "description": "otelcol metrics dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_version",
    "label": "service_version",
    "query": {
     "query": "query_result(sum(otelcol_process_uptime{}) by (service_version))\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Otel Collector Instance",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds_total{service_instance_id=~\".*\"}) by (service_instance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "gauge",
   "description": "otelcol_process_cpu_seconds",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds_total{}[$__rate_interval])*100) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory Rss\navg(otelcol_process_memory_rss{}) by (instance)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(otelcol_process_memory_rss{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "options": {
    "content": "## Opentelemetry Collector Data Ingress/Egress\n\n`service_version:` ${service_version}\n\n`opentelemetry collector:` contrib\n\n"
   }
  },
  { "title": "Trace Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Export Ratio",
   "type": "gauge",
   "description": "(avg(sum by(job) (rate(otelcol_exporter_sent_spans{}[$__range]))) / avg(sum by(job) (rate(otelcol_receiver_accepted_spans{}[$__range])))) ",
   "gridPos": { "h": 19, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(sum by(job) (rate(otelcol_exporter_sent_spans_total{}[$__range]))) / avg(sum by(job) (rate(otelcol_receiver_accepted_spans_total{}[$__range])))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "label_join(label_join(\n(rate(otelcol_receiver_accepted_spans_total{}[$__interval]))\n, \"id\", \"\", \"transport\", \"receiver\")\n, \"title\", \"\", \"transport\", \"receiver\")\n\nor\n\nlabel_replace(label_replace(\nsum by(service_name) (rate(otelcol_receiver_accepted_spans_total{}[$__interval]))\n, \"id\", \"processor\", \"dummynode\", \"\")\n, \"title\", \"processor\", \"dummynode\", \"\")\n\nor\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n\nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans_total{}[$__interval]))\n, \"id\", \"exporter\", \"dummynode\", \"\")\n, \"title\", \"exporter\", \"dummynode\", \"\")\n        \nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans_total{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_join(\n(rate(otelcol_receiver_accepted_spans_total{}[$__interval]))\n\n ,\"source\",\"\",\"transport\",\"receiver\")\n,\"target\",\"processor\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n  or\n\n  label_join(\nlabel_replace(label_replace(\n  (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n    (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n   (rate(otelcol_exporter_sent_spans_total{}[$__interval]))\n ,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "OpenTelemetry Collector",
 "description": "Visualize OpenTelemetry (OTEL) collector metrics (tested with OTEL contrib v0.113.0)",
 "tags": [
  "opentelemetry",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spans ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of spans successfully pushed into the pipeline.\nRefused: count/rate of spans that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_spans_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_spans_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  }
 ]
}
{
 "title": "Spanmetrics Demo Dashboard",
 "description": "Spanmetrics way of demo application view.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "query_result(count by (service_name)(count_over_time(traces_span_metrics_calls_total[$__range])))"
    }
   },
   {
    "name": "span_name",
    "query": {
     "query": "query_result(sum ({__name__=~\".*traces_span_metrics_calls_total\",service_name=~\"$service\"})  by (span_name))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Level - Throughput and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Top 3x3 - Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  }
 ]
}